### ISSUE TITLE
java.awt.HeadlessException

### ISSUE THREAD

**Issue by steve-ttt** [oakes/Nightmod#10]
I can't run the jar that I downloaded from the website ?

> [stephen@localhost clojure]$ java -jar nightmod-1.3.2-standalone.jar 
> Exception in thread "main" java.awt.HeadlessException
> 	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
> 	at nightmod.Nightmod.init(Nightmod.java:37)
> 	at nightmod.Nightmod.main(Nightmod.java:70)
> [stephen@localhost clojure]$ java -version
> openjdk version "1.8.0_101"
> OpenJDK Runtime Environment (build 1.8.0_101-b14)
> OpenJDK 64-Bit Server VM (build 25.101-b14, mixed mode)
> [stephen@localhost clojure]$ uname -a
> Linux localhost.localdomain 4.6.6-300.fc24.x86_64 #1 SMP Wed Aug 10 21:07:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oakes** [comment]
Hmm, I haven't seen this before. Are you running linux with a desktop environment / window manager? Seems like this error would happen when that isn't available.

**Comment by steve-ttt** [comment]
Fedora FC24 with Gnome 3.20.2

I can run jar files that I make under netbeans with awt
